"""initial schema

Revision ID: cb5e7dc71a88
Revises: 
Create Date: 2026-03-11 18:12:53.933847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5e7dc71a88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydroserver_connection',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('csv_delimiter', sa.String(length=10), nullable=False),
    sa.Column('csv_header_row', sa.Integer(), nullable=False),
    sa.Column('csv_timestamp_column', sa.String(length=255), nullable=False),
    sa.Column('csv_timestamp_format', sa.String(length=255), nullable=False),
    sa.Column('column_mappings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['hydroserver_connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_run',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('values_loaded_total', sa.Integer(), nullable=True),
    sa.Column('earliest_timestamp', sa.DateTime(), nullable=True),
    sa.Column('latest_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_run')
    op.drop_table('task')
    op.drop_table('hydroserver_connection')
    # ### end Alembic commands ###
