name: HydroLoader Build and AWS Distribution
run-name: ${{ github.actor }} is building HydroLoader on ${{ github.ref }}

on:
  release:
    types: [created]

jobs:
  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [ '3.10' ]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install dmgbuild

      - name: Build App
        run: |
          pyinstaller \
          --name 'HydroLoader' \
          --icon 'src/assets/app_icon.png' \
          --windowed \
          --onedir \
          --add-data 'src/assets/setup_icon.png:.' \
          --add-data 'src/assets/app_icon.png:.' \
          --add-data 'src/assets/tray_icon.png:.' \
          src/app.py

      - name: Package App DMG
        run: |
          dmgbuild \
          -s src/package/macos/settings.py \
          "Install HydroLoader" \
          HydroLoader.dmg

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'us-east-1'

      - name: Upload App DMG to AWS S3
        run: aws s3 cp HydroLoader.dmg s3://sdl-dist/${{ github.event.workflow_run.head_sha }}/macos/HydroLoader.dmg
