name: Streaming Data Loader Build and AWS Distribution - Updated
run-name: ${{ github.actor }} is building Streaming Data Loader on ${{ github.ref }}

on: workflow_dispatch

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller==5.13.0

      - name: Build App
        run: |
          pyinstaller \
          --name 'Streaming Data Loader' \
          --icon 'src/assets/app_icon.png' \
          --windowed \
          --onedir \
          --add-data 'src/assets/setup_icon.png:.' \
          --add-data 'src/assets/app_icon.png:.' \
          --add-data 'src/assets/tray_icon.png:.' \
          src/app.py

      - uses: actions/upload-artifact@v2
        with:
          name: sdl-ubuntu
          path: src/dist/linux
